### PR TITLE
Updated with Palo Alto Software

### PR DESCRIPTION
**Pull request by jivesx**
Updated with Palo Alto Software from https://docs.paloaltonetworks.com/oss-listings

Thank you for your contribution! Some pointers to get it merged quickly:

For contributions in `software/`:

  - [x] PR Title: Please use "Add <vendor/product name>" (instead of "Update README.md")
  - [x] Status: please select a value from the status table at the top
  - [x] Version: Status Vulnerable / Workaround? -> List vulnerable versions.
                 Status Fix?                     -> List fixed versions.
  - [x] Links: make sure you link to a public statement by the developer.
    Alternatively, include and link a file in the `software/vendor-statements/` directory
  - [x] Please mind the sorting

### CODE REVIEW

**Comment by jivesx** [comment]
Added software listed on the PAlo Alto Networks Open-Source Software (OSS) License pages which include versions.

**Comment by jspaans91** [comment]
@jivesx and @rkokkelk Palo Alto published a statement that all the products are not vulnerable. @jivesx maybe you can update your PR?

Link to the statement: https://security.paloaltonetworks.com/PAN-SA-2022-0006

**Comment by jspaans91** [comment]
The list is currently updated by pull request #40, so I think this PR can be closed.

**Comment by rkokkelk** [comment]
As specified by @jspaans91 this is resolved by #40

**Pull request closed without merging**
