### PR TITLE
Remove: Tenable Nessus, Agent and Network Agent

### PR DESCRIPTION
**Pull request by favroom**
The release notes of these products all state support for OpenSSL v3.0(.5). They don't have to be used with OpenSSL v3...

Thank you for your contribution! Some pointers to get it merged quickly:

For contributions in `software/`:

  - [x] PR Title: Please use "Add <vendor/product name>" (instead of "Update README.md")
  - [x] Status: please select a value from the status table at the top
  - [x] Version: Status Vulnerable / Workaround? -> List vulnerable versions.
                 Status Fix?                     -> List fixed versions.
  - [x] Links: make sure you link to a public statement by the developer.
    Alternatively, include and link a file in the `software/vendor-statements/` directory
  - [x] Please mind the sorting

### CODE REVIEW

**Comment by pbeij** [comment]
The software is vulnerable when a certain OpenSSL version is used (which is in the table OpenSSL 3.0.5)

**Comment by Kontsnor** [comment]
> > The software is vulnerable when a certain OpenSSL version is used (which is in the table OpenSSL 3.0.5)
> 
> Exactly. So shouldn't it then be labelled as Vulnerable but Fix available? As a fix would be not to use OpenSSL v3 but v1?

Nessus comes bundled with OpenSSL v3.0.5, it's stored somewhere in the `/opt/nessus` tree. Can't access the instance right now, so can't validate the exact path. Seems to me the solution would be to replace the binary that came bundled with Nessus with the 3.0.7 binary (or wait for an update from Nessus).

**Comment by ontkanin** [comment]
> Nessus comes bundled with OpenSSL v3.0.5, it's stored somewhere in the `/opt/nessus` tree. Can't access the instance right now, so can't validate the exact path. Seems to me the solution would be to replace the binary that came bundled with Nessus with the 3.0.7 binary (or wait for an update from Nessus).

I've checked Nessus docker container (maintained by Tenable), and the only `openssl` I can find in `/opt/nessus` are plugins for openssl detection

On the OS level (container):
```
sh-4.4# yum list openssl*
Last metadata expiration check: 0:00:30 ago on Tue Nov  1 20:15:42 2022.
Installed Packages
openssl-libs.x86_64                                              1:1.1.1k-7.el8_6                                         @System
Available Packages
openssl.src                                                      1:1.1.1k-7.el8_6                                         ol8_baseos_latest
openssl.x86_64                                                   1:1.1.1k-7.el8_6                                         ol8_baseos_latest
openssl-devel.i686                                               1:1.1.1k-7.el8_6                                         ol8_baseos_latest
openssl-devel.x86_64                                             1:1.1.1k-7.el8_6                                         ol8_baseos_latest
openssl-ibmpkcs11.src                                            1.0.2-1.el8                                              ol8_baseos_latest
openssl-ibmpkcs11.x86_64                                         1.0.2-1.el8                                              ol8_baseos_latest
openssl-libs.i686                                                1:1.1.1k-7.el8_6                                         ol8_baseos_latest
openssl-perl.x86_64                                              1:1.1.1k-7.el8_6                                         ol8_baseos_latest
openssl-pkcs11.i686                                              0.4.10-2.el8                                             ol8_baseos_latest
openssl-pkcs11.src                                               0.4.10-2.el8                                             ol8_baseos_latest
openssl-pkcs11.x86_64                                            0.4.10-2.el8                                             ol8_baseos_latest
sh-4.4#
```

**Comment by Kontsnor** [comment]
> > Nessus comes bundled with OpenSSL v3.0.5, it's stored somewhere in the `/opt/nessus` tree. Can't access the instance right now, so can't validate the exact path. Seems to me the solution would be to replace the binary that came bundled with Nessus with the 3.0.7 binary (or wait for an update from Nessus).
> 
> I've checked Nessus docker container (maintained by Tenable), and the only `openssl` I can find in `/opt/nessus` are plugins for openssl detection
> 
> On the OS level (container):
> 
> ```
> sh-4.4# yum list openssl*
> Last metadata expiration check: 0:00:30 ago on Tue Nov  1 20:15:42 2022.
> Installed Packages
> openssl-libs.x86_64                                              1:1.1.1k-7.el8_6                                         @System
> Available Packages
> openssl.src                                                      1:1.1.1k-7.el8_6                                         ol8_baseos_latest
> openssl.x86_64                                                   1:1.1.1k-7.el8_6                                         ol8_baseos_latest
> openssl-devel.i686                                               1:1.1.1k-7.el8_6                                         ol8_baseos_latest
> openssl-devel.x86_64                                             1:1.1.1k-7.el8_6                                         ol8_baseos_latest
> openssl-ibmpkcs11.src                                            1.0.2-1.el8                                              ol8_baseos_latest
> openssl-ibmpkcs11.x86_64                                         1.0.2-1.el8                                              ol8_baseos_latest
> openssl-libs.i686                                                1:1.1.1k-7.el8_6                                         ol8_baseos_latest
> openssl-perl.x86_64                                              1:1.1.1k-7.el8_6                                         ol8_baseos_latest
> openssl-pkcs11.i686                                              0.4.10-2.el8                                             ol8_baseos_latest
> openssl-pkcs11.src                                               0.4.10-2.el8                                             ol8_baseos_latest
> openssl-pkcs11.x86_64                                            0.4.10-2.el8                                             ol8_baseos_latest
> sh-4.4#
> ```

I see what you mean when running the container, the binary doesn't seem to be there. However it is there when you install the rpm. This is from a Alma 8 container with Nessus 10.4.0 freshly installed.

`[root@4ae3c657a67e bin]# /opt/nessus/bin/openssl version
OpenSSL 3.0.5 5 Jul 2022 (Library: OpenSSL 3.0.5 5 Jul 2022)`

**Comment by ontkanin** [comment]
> I see what you mean when running the container, the binary doesn't seem to be there. However it is there when you install the rpm. This is from a Alma 8 container with Nessus 10.4.0 freshly installed.
> 
> ```
> [root@4ae3c657a67e bin]# /opt/nessus/bin/openssl version
> OpenSSL 3.0.5 5 Jul 2022 (Library: OpenSSL 3.0.5 5 Jul 2022)
> ```

There is indeed an `openssl` binary when installing the latest Nessus from RPM:
```
$ rpm -qlp Nessus-10.4.0-es8.x86_64.rpm | grep openssl
warning: Nessus-10.4.0-es8.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 2f12969d: NOKEY
/opt/nessus/bin/openssl
```

That must be some recent change in their RPMs, because the latest `tenableofficial/nessus` Docker container is using `Nessus-10.3.0-es8.x86_64.rpm` and that one doesn't have `/opt/nessus/bin/openssl`. 

I guess I've been saved by Tenable's lack of discipline in releasing their updated Docker containers 😁

**Comment by Kontsnor** [comment]
> > I see what you mean when running the container, the binary doesn't seem to be there. However it is there when you install the rpm. This is from a Alma 8 container with Nessus 10.4.0 freshly installed.
> > ```
> > [root@4ae3c657a67e bin]# /opt/nessus/bin/openssl version
> > OpenSSL 3.0.5 5 Jul 2022 (Library: OpenSSL 3.0.5 5 Jul 2022)
> > ```
> 
> There is indeed an `openssl` binary when installing the latest Nessus from RPM:
> 
> ```
> $ rpm -qlp Nessus-10.4.0-es8.x86_64.rpm | grep openssl
> warning: Nessus-10.4.0-es8.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 2f12969d: NOKEY
> /opt/nessus/bin/openssl
> ```
> 
> That must be some recent change in their RPMs, because the latest `tenableofficial/nessus` Docker container is using `Nessus-10.3.0-es8.x86_64.rpm` and that one doesn't have `/opt/nessus/bin/openssl`.
> 
> I guess I've been saved by Tenable's lack of discipline in releasing their updated Docker containers 😁

What I commented earlier is also applicable for 10.3.0. Just not for the docker images somehow.

**Comment by ontkanin** [comment]
> What I commented earlier is also applicable for 10.3.0. Just not for the docker images somehow.

In that case, they must be using different RPMs for Docker containers than what they are otherwise distributing as RPM via their download page. The 10.3.0 RPM in their latest Docker container doesn't have `openssl` binaries:
```
sh-4.4# rpm -qi Nessus
Name        : Nessus
Version     : 10.3.0
Release     : es8
Architecture: x86_64
Install Date: Wed Sep 21 18:22:42 2022
Group       : Administration Tools
Size        : 81696387
License     : Proprietary
Signature   : RSA/SHA256, Sun Jul 10 15:10:50 2022, Key ID c3e60e421c0c4a5d
Source RPM  : Nessus-10.3.0-es8.src.rpm
Build Date  : Sun Jul 10 15:01:24 2022
Build Host  : ip-10-254-73-204.eu.build.aws.tenablesecurity.com
Relocations : (not relocatable)
Packager    : Renaud Deraison <rderaison@tenablesecurity.com>
URL         : http://www.nessus.org
Summary     : Nessus Scanner, supported by Tenable
Description :
The Nessus Vulnerability Scanner
sh-4.4#
sh-4.4# rpm -qil Nessus | grep openssl
sh-4.4#
```

**Comment by jspaans91** [comment]
@pbeij this PR is resolved with PR #117 and can be closed.

**Comment by pbeij** [comment]
Correct, will close this now.

**Pull request closed without merging**
